name: flutter_arc_text
description: Flutter widget that renders text along the arc with configurable radius.
version: 0.5.0
homepage: https://github.com/ookami-kb/flutter_arc_text

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  characters: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mews_pedantic: ^0.20.0
  vector_math: ^2.1.4

flutter:
  assets:
    - assets/
