name: flutter_arc_text
description: Flutter widget that renders text along the arc with configurable radius.
version: 0.4.1
homepage: https://github.com/ookami-kb/flutter_arc_text

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  characters: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.9.0
  mews_pedantic: ^0.2.1
  vector_math: ^2.1.0

flutter:
  assets:
    - assets/
