name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_arc_text:
    path: ../
  storybook_flutter: ^0.14.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.20.0

flutter:
  uses-material-design: true
